Fix bugs with closing streams
paust-team/pirius pull request #205
Opened 2023-01-31 04:48 UTC by 1dennispark

2023-01-31 05:10 UTC, elon0823 requested changes
데니스, 제가 어제 batching 빼는거 다 하면서 subscriber 부분도 너무 중복코드가 많은 것 같아서 수정중이었는데요 이내용 포함해서 PR 을 제가 올리면어떨까요? 어자피 테스트코드, CLI 등 바껴야하는부분도 있으니 제가 같이 다 해서 올리면 어떨까합니다

2023-01-31 05:10 UTC, elon0823 commented on agent/pubsub/retrievable_subscriber.go
> +		defer close(errStream)
이부분은 subscriber.go 에도 그대로 추가되어야할것같습니다.

2023-01-31 05:10 UTC, elon0823 commented on agent/pubsub/subscriber.go
> +
이걸 쓰는부분은 어디인가요?

2023-01-31 05:10 UTC, elon0823 commented on agent/pubsub/retrievable_subscriber.go
> +	SendBack func([]SubscriptionResult) error
관련 test, cli 도 수정되어야할것같습니다

2023-01-31 09:08 UTC, 1dennispark commented on agent/pubsub/retrievable_subscriber.go
> +		defer close(errStream)
이미 추가되어 있습니다.

2023-01-31 09:08 UTC, 1dennispark commented
@elon0823 그래도 좋겠네요 ㅎ

이 PR은 닫고 그럼 커밋만 가져가서 PR 올려주시면 감사하겠습니다.

2023-02-01 02:00 UTC, 1dennispark commented on agent/pubsub/subscriber.go
> +
안쓰네요. 삭제하겠습니다.

2023-02-01 02:22 UTC, 1dennispark commented on agent/pubsub/retrievable_subscriber.go
> +	SendBack func([]SubscriptionResult) error
수정했습니다.

2023-02-01 02:22 UTC, 1dennispark commented
일단 여기에 Test와 CLI도 수정해서 진행하도록 할게요.

2023-02-01 02:22 UTC, elon0823 commented on agent/pubsub/retrievable_subscriber.go
> +	SendBack func([]SubscriptionResult) error
넵 Agent test 한번 돌려보셨을까요?

2023-02-01 05:16 UTC, 1dennispark commented on agent/pubsub/retrievable_subscriber.go
> +	SendBack func([]SubscriptionResult) error
넵 성공하는거 확인했습니다.

2023-02-01 05:18 UTC, elon0823 approved these changes

2023-02-01 05:26 UTC, merged